name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy all files to /app/code
      run: |
        rsync -av --delete ./ /app/code/

    - name: Build and Deploy with Docker Compose
      run: |
        cd /app/code
        docker compose build
        docker compose up -d --force-recreate